### ISSUE TITLE
[Question] Project Status

### ISSUE THREAD

**Issue by arky** [parsingphase/batbox#20]
@parsingphase Am evaluating using batbox for project out here in SE. Asia. Would love to know if the project is actively maintained and updated to Python3.

**Comment by parsingphase** [comment]
HI @arky - unfortunately this project is not under active maintenance at the time, but it has been running on Python 3.8 (which is still [receiving security updates](https://devguide.python.org/versions/)) since I first started work on it.

You are more than welcome to take and update the code as needed, but while I'd love to see the code used I regrettably have minimal time to support it, though I may be able to help with specific queries.

**Comment by arky** [comment]
@parsingphase Thank you! I'll check out the code and start looking at it. Will also drop you an email with details about my use case.
